### ISSUE TITLE
is bundler.rb missing in eycap-0.4.14?

### ISSUE THREAD

**Issue by rgo** [engineyard/eycap#1]
Hi,

   I have an app that uses this gem(I reinstalled eycap-0.4.14). But now my deploy no works anymore, it said:

```
cap staging deploy
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- eycap/recipes/bundler (LoadError)
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/engineyard-eycap-0.4.14/lib/eycap/recipes.rb:18
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/configuration/loading.rb:152:in `require'
    from ./config/deploy.rb:4:in `load'
    from /usr/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/configuration/loading.rb:172:in `load_from_file'
    from /usr/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/configuration/loading.rb:89:in `load'
     ... 13 levels...
    from /usr/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/cli/execute.rb:14:in `execute'
    from /usr/lib/ruby/gems/1.8/gems/capistrano-2.5.9/bin/cap:4
    from /usr/bin/cap:19:in `load'
    from /usr/bin/cap:19
```

I was searching this file in /usr/lib/ruby/gems/1.8/gems/engineyard-eycap-0.4.14/lib/eycap/recipes/ and it don't exists.

Is missing that file in the gem?

Thanks

**Comment by rgo** [comment]
I sent to you a pull request with the fix 2 days ago and yesterday you fixed it. 

This issue can be closeed.
