### ISSUE TITLE
undefined method `enable' for #<Capistrano::Configuration::Namespaces::Namespace:0x007f947588a8b8> (NoMethodError)

### ISSUE THREAD

**Issue by ghazel** [engineyard/eycap#38]
``` ruby
ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/configuration/namespaces.rb:193:in `method_missing': undefined method `enable' for #<Capistrano::Configuration::Namespaces::Namespace:0x007f947588a8b8> (NoMethodError)
    from ruby-1.9.3-p194/gems/eycap-0.6.6/lib/eycap/recipes/deploy.rb:70:in `block (3 levels) in <top (required)>'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:45:in `each'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:34:in `execute!'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:14:in `execute'
    from ruby-1.9.3-p194/gems/capistrano-2.14.2/bin/cap:4:in `<top (required)>'
    from ruby-1.9.3-p194/bin/cap:19:in `load'
    from ruby-1.9.3-p194/bin/cap:19:in `<main>'
    from ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by ghazel** [comment]
This bug was introduced by Capistrano: https://github.com/capistrano/capistrano/commit/4ece7902d5058

**Comment by 7hunderbird** [comment]
This has been added back to the latest capistrano version 2.15.x tree. 

https://github.com/capistrano/capistrano/blob/v2.15.4/lib/capistrano/recipes/deploy.rb#L557-L624

Closing issue.

**Comment by donjohnson** [comment]
(disregard, I was simply subscribed, and this is actually a public repo..my
bad!)
